// Copyright 2012 Google Inc. All Rights Reserved.

package com.google.typography.font.sfntly.table.opentype;

import com.google.typography.font.sfntly.Tag;

import java.util.Arrays;
import java.util.List;

/**
 * @author dougfelt@google.com (Doug Felt)
 *
 * @see "ISO-IEC 14496-22:2015, c066391_ISO_IEC_14496-22_2015.pdf, pages 318 to 338"
 */
enum LanguageTag {
  ABA("Abaza", "abq"),
  ABK("Abkhazian", "abk"),
  ACH("Acholi", "ach"),
  ACR("Achi", "acr"),
  ADY("Adyghe", "ady"),
  AFK("Afrikaans", "afr"),
  AFR("Afar", "aar"),
  AGW("Agaw", "ahg"),
  AIO("Aiton", "aio"),
  AKA("Akan", "aka"),
  ALS("Alsatian", "gsw"),
  ALT("Altai", "atv,alt"),
  AMH("Amharic", "amh"),
  ANG("Anglo-Saxon", "ang"),
  APPH("Phonetic transcription – Americanist conventions", ""),
  ARA("Arabic", "ara"),
  ARG("Aragonese", "arg"),
  ARI("Aari", "aiw"),
  ARK("Rakhine", "mhv,rmz,rki"),
  ASM("Assamese", "asm"),
  AST("Asturian", "ast"),
  ATH("Athapaskan", ""
          + "apk,apj,apl,apm,apw,nav,bea,sek,bcr,caf,"
          + "crx,clc,gwi,haa,chp,dgr,scs,xsl,srs,ing,"
          + "hoi,koy,hup,ktw,mvb,wlk,coq,ctc,gce,tol,"
          + "tuu,kkz,tgx,tht,aht,tfn,taa,tau,tcb,kuu,"
          + "tce,ttm,txc"),
  AVR("Avar", "ava"),
  AWA("Awadhi", "awa"),
  AYM("Aymara", "aym"),
  AZB("Torki", "azb"),
  AZE("Azerbaijani", "aze"),
  BAD("Badaga", "bfq"),
  BAD0("Banda", "bad"),
  BAG("Baghelkhandi", "bfy"),
  BAL("Balkar", "krc"),
  BAN("Balinese", "ban"),
  BAR("Bavarian", "bar"),
  BAU("Baoulé", "bci"),
  BBC("Batak Toba", "bbc"),
  BBR("Berber", ""),
  BCH("Bench", "bcq"),
  BCR("Bible Cree", ""),
  BDY("Bandjalang", "bdy"),
  BEL("Belarusian", "bel"),
  BEM("Bemba", "bem"),
  BEN("Bengali", "ben"),
  BGC("Haryanvi", "bgc"),
  BGQ("Bagri", "bgq"),
  BGR("Bulgarian", "bul"),
  BHI("Bhili", "bhi,bhb"),
  BHO("Bhojpuri", "bho"),
  BIK("Bikol", "bik,bhk,bcl,bto,cts,bln"),
  BIL("Bilen", "byn"),
  BIS("Bislama", "bis"),
  BJJ("Kanauji", "bjj"),
  BKF("Blackfoot", "bla"),
  BLI("Baluchi", "bal"),
  BLK("Pa'o Karen", "blk"),
  BLN("Balante", "bjt,ble"),
  BLT("Balti", "bft"),
  BMB("Bambara (Bamanankan)", "bam"),
  BML("Bamileke", ""),
  BOS("Bosnian", "bos"),
  BPY("Bishnupriya Manipuri", "bpy"),
  BRE("Breton", "bre"),
  BRH("Brahui", "brh"),
  BRI("Braj Bhasha", "bra"),
  BRM("Burmese", "mya"),
  BRX("Bodo", "brx"),
  BSH("Bashkir", "bak"),
  BTI("Beti", "btb"),
  BTS("Batak Simalungun", "bts"),
  BUG("Bugis", "bug"),
  CAK("Kaqchikel", "cak"),
  CAT("Catalan", "cat"),
  CBK("Zamboanga Chavacano", "cbk"),
  CEB("Cebuano", "ceb"),
  CHE("Chechen", "che"),
  CHG("Chaha Gurage", "sgw"),
  CHH("Chattisgarhi", "hne"),
  CHI("Chichewa (Chewa, Nyanja)", "nya"),
  CHK("Chukchi", "ckt"),
  CHK0("Chuukese", "chk"),
  CHO("Choctaw", "cho"),
  CHP("Chipewyan", "chp"),
  CHR("Cherokee", "chr"),
  CHA("Chamorro", "cha"),
  CHU("Chuvash", "chv"),
  CHY("Cheyenne", "chy"),
  CGG("Chiga", "cgg"),
  CMR("Comorian", "swb,wlc,wni,zdj"),
  COP("Coptic", "cop"),
  COR("Cornish", "cor"),
  COS("Corsican", "cos"),
  CPP("Creoles", "cpp"),
  CRE("Cree", "cre"),
  CRR("Carrier", "crx,caf"),
  CRT("Crimean Tatar", "crh"),
  CSB("Kashubian", "csb"),
  CSL("Church Slavonic", "chu"),
  CSY("Czech", "ces"),
  CTG("Chittagonian", "ctg"),
  CUK("San Blas Kuna", "cuk"),
  DAN("Danish", "dan"),
  DAR("Dargwa", "dar"),
  DAX("Dayi", "dax"),
  DCR("Woods Cree", "cwd"),
  DEU("German", "deu"),
  DGO("Dogri", "dgo"),
  DGR("Dogri", "doi"),
  DHG("Dhangu", "dhg"),
  DHV("Divehi (Dhivehi, Maldivian)", "div"), // deprecated
  DIQ("Dimli", "diq"),
  DIV("Divehi (Dhivehi, Maldivian)", "div"),
  DJR("Zarma", "dje"),
  DJR0("Djambarrpuyngu", "djr"),
  DNG("Dangme", "ada"),
  DNJ("Dan", "dnj"),
  DNK("Dinka", "din"),
  DRI("Dari", "prs"),
  DUJ("Dhuwal", "duj"),
  DUN("Dungan", "dng"),
  DZN("Dzongkha", "dzo"),
  EBI("Ebira", "igb"),
  ECR("Eastern Cree", "crj,crl"),
  EDO("Edo", "bin"),
  EFI("Efik", "efi"),
  ELL("Greek", "ell"),
  EMK("Eastern Maninkakan", "emk"),
  ENG("English", "eng"),
  ERZ("Erzya", "myv"),
  ESP("Spanish", "spa"),
  ESU("Central Yupik", "esu"),
  ETI("Estonian", "est"),
  EUQ("Basque", "eus"),
  EVK("Evenki", "evn"),
  EVN("Even", "eve"),
  EWE("Ewe", "ewe"),
  FAN("French Antillean", "acf"),
  FAN0("Fang", "fan"),
  FAR("Persian", "fas"),
  FAT("Fanti", "fat"),
  FIN("Finnish", "fin"),
  FJI("Fijian", "fij"),
  FLE("Dutch (Flemish)", "vls"),
  FNE("Forest Nenets", "enf"),
  FON("Fon", "fon"),
  FOS("Faroese", "fao"),
  FRA("French", "fra"),
  FRC("Cajun French", "frc"),
  FRI("Frisian", "fry"),
  FRL("Friulian", "fur"),
  FRP("Arpitan", "frp"),
  FTA("Futa", "fuf"),
  FUL("Fulah", "ful"),
  FUV("Nigerian Fulfulde", "fuv"),
  GAD("Ga", "gaa"),
  GAE("Scottish Gaelic (Gaelic)", "gla"),
  GAG("Gagauz", "gag"),
  GAL("Galician", "glg"),
  GAR("Garshuni", ""),
  GAW("Garhwali", "gbm"),
  GEZ("Ge'ez", "gez"),
  GIH("Githabul", "gih"),
  GIL("Gilyak", "niv"),
  GIL0("Kiribati (Gilbertese)", "gil"),
  GKP("Kpelle (Guinea)", "gkp"),
  GLK("Gilaki", "glk"),
  GMZ("Gumuz", "guk"),
  GNN("Gumatj", "gnn"),
  GOG("Gogo", "gog"),
  GON("Gondi", "gon,gno,ggo"),
  GRN("Greenlandic", "kal"),
  GRO("Garo", "grt"),
  GUA("Guarani", "grn"),
  GUC("Wayuu", "guc"),
  GUF("Gupapuyngu", "guf"),
  GUJ("Gujarati", "guj"),
  GUZ("Gusii", "guz"),
  HAI("Haitian (Haitian Creole)", "hat"),
  HAL("Halam", "flm"),
  HAR("Harauti", "hoj"),
  HAU("Hausa", "hau"),
  HAW("Hawaiian", "haw"),
  HAY("Haya", "hay"),
  HAZ("Hazaragi", "haz"),
  HBN("Hammer-Banna", "amf"),
  HER("Herero", "her"),
  HIL("Hiligaynon", "hil"),
  HIN("Hindi", "hin"),
  HMA("High Mari", "mrj"),
  HMN("Hmong", "hmn"),
  HMO("Hiri Motu", "hmo"),
  HND("Hindko", "hno,hnd"),
  HO("Ho", "hoc"),
  HRI("Harari", "har"),
  HRV("Croatian", "hrv"),
  HUN("Hungarian", "hun"),
  HYE("Armenian", "hye"),
  HYE0("Armenian East", "hye"),
  IBA("Iban", "iba"),
  IBB("Ibibio", "ibb"),
  IBO("Igbo", "ibo"),
  IJO("Ijo languages", "ijc"),
  IDO("Ido", "ido"),
  ILE("Interlingue", "ile"),
  ILO("Ilokano", "ilo"),
  INA("Interlingua", "ina"),
  IND("Indonesian", "ind"),
  ING("Ingush", "inh"),
  INU("Inuktitut", "iku"),
  IPK("Inupiat", "ipk"),
  IPPH("Phonetic transcription – IPA conventions", ""),
  IRI("Irish", "gle"),
  IRT("Irish Traditional", "gle"),
  ISL("Icelandic", "isl"),
  ISM("Inari Sami", "smn"),
  ITA("Italian", "ita"),
  IWR("Hebrew", "heb"),
  JAV("Javanese", "jav"),
  JII("Yiddish", "yid"),
  JAM("Jamaican Creole", "jam"),
  JAN("Japanese", "jpn"),
  JBO("Lojban", "jbo"),
  JUD("Ladino", "lad"),
  JUL("Jula", "dyu"),
  KAB("Kabardian", "kbd"),
  KAB0("Kabyle", "kab"),
  KAC("Kachchi", "kfr"),
  KAL("Kalenjin", "kln"),
  KAN("Kannada", "kan"),
  KAR("Karachay", "krc"),
  KAT("Georgian", "kat"),
  KAZ("Kazakh", "kaz"),
  KDE("Makonde", "kde"),
  KEA("Kabuverdianu (Crioulo)", "kea"),
  KEB("Kebena", "ktb"),
  KEK("Kekchi", "kek"),
  KGE("Khutsuri Georgian", "kat"),
  KHA("Khakass", "kjh"),
  KHK("Khanty-Kazim", "kca"),
  KHM("Khmer", "khm"),
  KHS("Khanty-Shurishkar", "kca"),
  KHT("Khamti Shan", "kht"),
  KHV("Khanty-Vakhi", "kca"),
  KHW("Khowar", "khw"),
  KIK("Kikuyu (Gikuyu)", "kik"),
  KIR("Kirghiz (Kyrgyz)", "kir"),
  KIS("Kisii", "kqs,kss"),
  KIU("Kirmanjki", "kiu"),
  KJD("Southern Kiwai", "kjd"),
  KJP("Eastern Pwo Karen", "kjp"),
  KKN("Kokni", "kex"),
  KLM("Kalmyk", "xal"),
  KMB("Kamba", "kam"),
  KMN("Kumaoni", "kfy"),
  KMO("Komo", "kmw"),
  KMS("Komso", "kxc"),
  KNR("Kanuri", "kau"),
  KOD("Kodagu", "kfa"),
  KOH("Korean Old Hangul", "okm"),
  KOK("Konkani", "kok"),
  KON("Kikongo", "ktu"),
  KON0("Kongo", "kon"),
  KOM("Komi", "kom"),
  KOP("Komi-Permyak", "koi"),
  KOR("Korean", "kor"),
  KOS("Kosraean", "kos"),
  KOZ("Komi-Zyrian", "kpv"),
  KPL("Kpelle", "kpe"),
  KRI("Krio", "kri"),
  KRK("Karakalpak", "kaa"),
  KRL("Karelian", "krl"),
  KRM("Karaim", "kdr"),
  KRN("Karen", "kar"),
  KRT("Koorete", "kqy"),
  KSH("Kashmiri", "kas"),
  KSH0("Ripuarian", "ksh"),
  KSI("Khasi", "kha"),
  KSM("Kildin Sami", "sjd"),
  KSW("S’gaw Karen", "ksw"),
  KUA("Kuanyama", "kua"),
  KUI("Kui", "kxu"),
  KUL("Kulvi", "kfx"),
  KUM("Kumyk", "kum"),
  KUR("Kurdish", "kur"),
  KUU("Kurukh", "kru"),
  KUY("Kuy", "kdt"),
  KYK("Koryak", "kpy"),
  KYU("Western Kayah", "kyu"),
  LAD("Ladin", "lld"),
  LAH("Lahuli", "bfu"),
  LAK("Lak", "lbe"),
  LAM("Lambani", "lmn"),
  LAO("Lao", "lao"),
  LAT("Latin", "lat"),
  LAZ("Laz", "lzz"),
  LCR("L-Cree", "crm"),
  LDK("Ladakhi", "lbj"),
  LEZ("Lezgi", "lez"),
  LIJ("Ligurian", "lij"),
  LIM("Limburgish", "lim"),
  LIN("Lingala", "lin"),
  LIS("Lisu", "lis"),
  LJP("Lampung", "ljp"),
  LKI("Laki", "lki"),
  LMA("Low Mari", "mhr"),
  LMB("Limbu", "lif"),
  LMO("Lombard", "lmo"),
  LMW("Lomwe", "ngl"),
  LOM("Loma", "lom"),
  LRC("Luri", "lrc,luz,bqi,zum"),
  LSB("Lower Sorbian", "dsb"),
  LSM("Lule Sami", "smj"),
  LTH("Lithuanian", "lit"),
  LTZ("Luxembourgish", "ltz"),
  LUA("Luba-Lulua", "lua"),
  LUB("Luba-Katanga", "lub"),
  LUG("Ganda", "lug"),
  LUH("Luyia", "luy"),
  LUO("Luo", "luo"),
  LVI("Latvian", "lav"),
  MAD("Madura", "mad"),
  MAG("Magahi", "mag"),
  MAH("Marshallese", "mah"),
  MAJ("Majang", "mpe"),
  MAK("Makhuwa", "vmw"),
  MAL("Malayalam Traditional", "mal"),
  MAM("Mam", "mam"),
  MAN("Mansi", "mns"),
  MAP("Mapudungun", "arn"),
  MAR("Marathi", "mar"),
  MAW("Marwari", "mwr,dhd,rwr,mve,wry,mtr,swv"),
  MBN("Mbundu", "kmb"),
  MCH("Manchu", "mnc"),
  MCR("Moose Cree", "crm"),
  MDE("Mende", "men"),
  MDR("Mandar", "mdr"),
  MEN("Me'en", "mym"),
  MER("Meru", "mer"),
  MFE("Morisyen", "mfe"),
  MIN("Minangkabau", "min"),
  MIZ("Mizo", "lus"),
  MKD("Macedonian", "mkd"),
  MKR("Makasar", "mak"),
  MKW("Kituba", "mkw"),
  MLE("Male", "mdy"),
  MLG("Malagasy", "mlg"),
  MLN("Malinke", "mlq"),
  MLR("Malayalam Reformed", "mal"),
  MLY("Malay", "msa"),
  MND("Mandinka", "mnk"),
  MNG("Mongolian", "mon"),
  MNI("Manipuri", "mni"),
  MNK("Maninka", "man,mnk,myq,mku,msc,emk,mwk,mlq"),
  MNX("Manx", "glv"),
  MOH("Mohawk", "mho"),
  MOK("Moksha", "mdf"),
  MOL("Moldavian", "mol"),
  MON("Mon", "mnw"),
  MOR("Moroccan", ""),
  MOS("Mossi", "mos"),
  MRI("Maori", "mri"),
  MTH("Maithili", "mai"),
  MTS("Maltese", "mlt"),
  MUN("Mundari", "unr"),
  MUS("Muscogee", "mus"),
  MWL("Mirandese", "mwl"),
  MWW("Hmong Daw", "mww"),
  MYN("Mayan", "myn"),
  MZN("Mazanderani", "mzn"),
  NAG("Naga-Assamese", "nag"),
  NAH("Nahuatl", "nah"),
  NAN("Nanai", "gld"),
  NAP("Neapolitan", "nap"),
  NAS("Naskapi", "nsk"),
  NAU("Nauruan", "nau"),
  NAV("Navajo", "nav"),
  NCR("N-Cree", "csw"),
  NDB("Ndebele", "nbl,nde"),
  NDC("Ndau", "ndc"),
  NDG("Ndonga", "ndo"),
  NDS("Low Saxon", "nds"),
  NEP("Nepali", "nep"),
  NEW("Newari", "new"),
  NGA("Ngbaka", "nga"),
  NGR("Nagari", ""),
  NHC("Norway House Cree", "csw"),
  NIS("Nisi", "dap"),
  NIU("Niuean", "niu"),
  NKL("Nyankole", "nyn"),
  NKO("N'Ko", "ngo"),
  NLD("Dutch", "nld"),
  NOE("Nimadi", "noe"),
  NOG("Nogai", "nog"),
  NOR("Norwegian", "nob"),
  NOV("Novial", "nov"),
  NSM("Northern Sami", "sme"),
  NSO("Sotho, Northern", "nso"),
  NTA("Northern Thai", "nod"),
  NTO("Esperanto", "epo"),
  NYM("Nyamwezi", "nym"),
  NYN("Norwegian Nynorsk (Nynorsk, Norwegian)", "nno"),
  OCI("Occitan", "oci"),
  OCR("Oji-Cree", "ojs"),
  OJB("Ojibway", "oji"),
  ORI("Odia (formerly Oriya)", "ori"),
  ORO("Oromo", "orm"),
  OSS("Ossetian", "oss"),
  PAA("Palestinian Aramaic", "sam"),
  PAG("Pangasinan", "pag"),
  PAL("Pali", "pli"),
  PAM("Pampangan", "pam"),
  PAN("Punjabi", "pan"),
  PAP("Palpa", "plp"),
  PAP0("Papiamentu", "pap"),
  PAS("Pashto", "pus"),
  PAU("Palauan", "pau"),
  PCC("Bouyei", "pcc"),
  PCD("Picard", "pcd"),
  PDC("Pennsylvania German", "pdc"),
  PGR("Polytonic Greek", "ell"),
  PHK("Phake", "phk"),
  PIH("Norfolk", "pih"),
  PIL("Filipino", "fil"),
  PLG("Palaung", "pce,rbb,pll"),
  PLK("Polish", "pol"),
  PMS("Piemontese", "pms"),
  PNB("Western Panjabi", "pnb"),
  POH("Pocomchi", "poh"),
  PON("Pohnpeian", "pon"),
  PRO("Provencal", "pro"),
  PTG("Portuguese", "por"),
  PWO("Western Pwo Karen", "pwo"),
  QIN("Chin", ""
          + "bgr,cnh,cnw,czt,sez,tcp,csy,ctd,flm,pck,"
          + "tcz,zom,cmr,dao,hlt,cka,cnk,mrh,mwg,cbl,"
          + "cnb,csh"),
  QUC("K’iche’", "quc"),
  QUH("Quechua (Bolivia)", "quh"),
  QUZ("Quechua", "quz"),
  QVI("Quechua (Ecuador)", "qvi"),
  QWH("Quechua (Peru)", "qwh"),
  RAJ("Rajasthani", "raj"),
  RAR("Rarotongan", "rar"),
  RCR("R-Cree", "atj"),
  RBU("Russian Buriat", "bxr"),
  REJ("Rejang", "rej"),
  RIA("Riang", "ria"),
  RIF("Tarifit", "rif"),
  RIT("Ritarungo", "rit"),
  RKW("Arakwal", "rkw"),
  RMS("Romansh", "roh"),
  RMY("Vlax Romani", "rmy"),
  ROM("Romanian", "ron"),
  ROY("Romany", "rom"),
  RSY("Rusyn", "rue"),
  RTM("Rotuman", "rtm"),
  RUA("Kinyarwanda", "kin"),
  RUN("Rundi", "run"),
  RUP("Aromanian", "rup"),
  RUS("Russian", "rus"),
  SAD("Sadri", "sck"),
  SAN("Sanskrit", "san"),
  SAS("Sasak", "sas"),
  SAT("Santali", "sat"),
  SAY("Sayisi", "chp"),
  SCN("Sicilian", "scn"),
  SCO("Scots", "sco"),
  SEK("Sekota", "xan"),
  SEL("Selkup", "sel"),
  SGA("Old Irish", "sga"),
  SGO("Sango", "sag"),
  SGS("Samogitian", "sgs"),
  SHI("Tachelhit", "shi"),
  SHN("Shan", "shn"),
  SIB("Sibe", "sjo"),
  SID("Sidamo", "sid"),
  SIG("Silte Gurage", "xst"),
  SKS("Skolt Sami", "sms"),
  SKY("Slovak", "slk"),
  SLA("Slavey", "scs"),
  SLV("Slovenian", "slv"),
  SML("Somali", "som"),
  SMO("Samoan", "smo"),
  SNA("Sena", "she"),
  SNA0("Shona", "sna"),
  SND("Sindhi", "snd"),
  SNH("Sinhala (Sinhalese)", "sin"),
  SNK("Soninke", "snk"),
  SOG("Sodo Gurage", "gru"),
  SOP("Songe", "sop"),
  SOT("Sotho, Southern", "sot"),
  SQI("Albanian", "gsw"),
  SRB("Serbian", "srp"),
  SRD("Sardinian", "srd"),
  SRK("Seraiki", "skr"),
  SRR("Serer", "srr"),
  SSL("South Slavey", "xsl"),
  SSM("Southern Sami", "sma"),
  STQ("Saterland Frisian", "stq"),
  SUK("Sukuma", "suk"),
  SUN("Sundanese", "sun"),
  SUR("Suri", "suq"),
  SVA("Svan", "sva"),
  SVE("Swedish", "swe"),
  SWA("Swadaya Aramaic", "aii"),
  SWK("Swahili", "swa"),
  SWZ("Swati", "ssw"),
  SXT("Sutu", "ngo"),
  SXU("Upper Saxon", "sxu"),
  SYL("Sylheti", "syl"),
  SYR("Syriac", "syr"),
  SZL("Silesian", "szl"),
  TAB("Tabasaran", "tab"),
  TAJ("Tajik", "tgk"),
  TAM("Tamil", "tam"),
  TAT("Tatar", "tat"),
  TCR("TH-Cree", "cwd"),
  TDD("Dehong Dai", "tdd"),
  TEL("Telugu", "tel"),
  TET("Tetum", "tet"),
  TGL("Tagalog", "tgl"),
  TGN("Tongan", "ton"),
  TGR("Tigre", "tig"),
  TGY("Tigrinya", "tir"),
  THA("Thai", "tha"),
  THT("Tahitian", "tah"),
  TIB("Tibetan", "bod"),
  TIV("Tiv", "tiv"),
  TKM("Turkmen", "tuk"),
  TMH("Tamashek", "tmh"),
  TMN("Temne", "tem"),
  TNA("Tswana", "tsn"),
  TNE("Tundra Nenets", "enh"),
  TNG("Tonga", "toi"),
  TOD("Todo", "xal"),
  TOD0("Toma", "tod"),
  TPI("Tok Pisin", "tpi"),
  TRK("Turkish", "tur"),
  TSG("Tsonga", "tso"),
  TUA("Turoyo Aramaic", "tru"),
  TUL("Tulu", "tcy"),
  TUM("Tumbuka", "tum"),
  TUV("Tuvin", "tyv"),
  TVL("Tuvalu", "tvl"),
  TWI("Twi", "twi"),
  TYZ("Tày", "tyz"),
  TZM("Tamazight", "tzm"),
  TZO("Tzotzil", "tzo"),
  UDM("Udmurt", "udm"),
  UKR("Ukrainian", "ukr"),
  UMB("Umbundu", "umb"),
  URD("Urdu", "urd"),
  USB("Upper Sorbian", "hsb"),
  UYG("Uyghur", "uig"),
  UZB("Uzbek", "uzb,uzn,uzs"),
  VEC("Venetian", "vec"),
  VEN("Venda", "ven"),
  VIT("Vietnamese", "vie"),
  VOL("Volapük", "vol"),
  VRO("Võro", "vro"),
  WA("Wa", "wbm"),
  WAG("Wagdi", "wbr"),
  WAR("Waray-Waray", "war"),
  WCR("West-Cree", "crk"),
  WEL("Welsh", "cym"),
  WLN("Walloon", "wln"),
  WLF("Wolof", "wol"),
  WTM("Mewati", "wtm"),
  XBD("Lü", "khb"),
  XHS("Xhosa", "xho"),
  XJB("Minjangbal", "xjb"),
  XOG("Soga", "xog"),
  XPE("Kpelle (Liberia)", "xpe"),
  YAK("Sakha", "sah"),
  YAO("Yao", "yao"),
  YAP("Yapese", "yap"),
  YBA("Yoruba", "yor"),
  YCR("Y-Cree", "cre"),
  YIC("Yi Classic", ""),
  YIM("Yi Modern", "iii"),
  ZEA("Zealandic", "zea"),
  ZGH("Standard Morrocan Tamazigh", "zgh"),
  ZHA("Zhuang", "zha"),
  ZHH("Chinese, Hong Kong SAR", "zho"),
  ZHP("Chinese Phonetic", "zho"),
  ZHS("Chinese Simplified", "zho"),
  ZHT("Chinese Traditional", "zho"),
  ZND("Zande", "zne"),
  ZUL("Zulu", "zul"),
  ZZA("Zazaki", "zza"),

  CHN("Chinese -- as seen in win7 kaiu.ttf", "zho"),
  DFLT("default", ""),
  KHN("Khun(?)", "kkh"),

  de("German found in FreeSerif.ttf", "deu"),
  nl("Dutch found in FreeSansBoldOblique.ttf", "nld"),
  tmh("Tamashek found in ebrimabd.ttf", "tmh");

  LanguageTag(String name, String iso3List) {
    this.tag = Tag.intValue((name() + "    ").substring(0, 4));
    this.name = name;
    this.iso3List = iso3List;
  }

  public int tag() {
    return tag;
  }

  public String longName() {
    return name;
  }

  public boolean isDeprecated() {
    return this == DHV;
  }

  public List<String> iso3List() {
    return Arrays.asList(iso3List.split(","));
  }

  static LanguageTag fromTag(int tag) {
    for (LanguageTag script : LanguageTag.values()) {
      if (script.tag == tag) {
        return script;
      }
    }
    throw new IllegalArgumentException(Tag.stringValue(tag));
  }

  private final int tag;
  private final String name;
  private final String iso3List;
}
