/*
 * !!! DO NOT EDIT !!!
 * THIS FILE IS GENERATED BY A SCRIPT.
 * FOR MORE DETAILS SEE 'README-test_data.txt'.
 */

/*
 * Copyright 2011 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SFNTLY_CPP_SRC_TEST_CMAP_TEST_DATA_H_
#define SFNTLY_CPP_SRC_TEST_CMAP_TEST_DATA_H_

#include "sfntly/port/type.h"

namespace sfntly
{
  struct ProtoCMap
  {
    int32_t length;
    int32_t format;
    int32_t platform_id;
    int32_t encoding_id;
    int32_t num_mappings;
    int32_t chars[10];
    int32_t glyph_ids[10];
  };

  struct TestCMap
  {
    const char *name;
    int32_t num_cmaps;
    ProtoCMap cmaps[2];
  };

  extern TestCMap kTestCousine_BoldItalic_ttf_xml;
  extern TestCMap kTestCousine_Bold_ttf_xml;
  extern TestCMap kTestCousine_Regular_ttf_xml;
  extern TestCMap kTestCousine_Italic_ttf_xml;
  extern TestCMap kTestCedarville_Cursive_ttf_xml;
  extern TestCMap kTestDancingScript_Bold_ttf_xml;
  extern TestCMap kTestDancingScript_Regular_ttf_xml;
  extern TestCMap kTestDamion_Regular_ttf_xml;
  extern TestCMap kTestAnnieUseYourTelescope_ttf_xml;
  extern TestCMap kTestDeliusSwashCaps_Regular_ttf_xml;
  extern TestCMap kTestDelius_Regular_ttf_xml;
  extern TestCMap kTestCoveredByYourGrace_ttf_xml;
  extern TestCMap kTestEBGaramond_Regular_ttf_xml;
  extern TestCMap kTestCabinSketch_Bold_ttf_xml;
  extern TestCMap kTestAllan_Bold_ttf_xml;
  extern TestCMap kTestCoda_Caption_Heavy_ttf_xml;
  extern TestCMap kTestCoda_Heavy_ttf_xml;
  extern TestCMap kTestForum_Regular_ttf_xml;
  extern TestCMap kTestAlike_Regular_ttf_xml;
  extern TestCMap kTestCorben_Bold_ttf_xml;
  extern TestCMap kTestCaudex_Regular_ttf_xml;
  extern TestCMap kTestCaudex_BoldItalic_ttf_xml;
  extern TestCMap kTestCaudex_Italic_ttf_xml;
  extern TestCMap kTestCaudex_Bold_ttf_xml;
  extern TestCMap kTestCabin_MediumItalic_ttf_xml;
  extern TestCMap kTestCabin_SemiBold_ttf_xml;
  extern TestCMap kTestCabin_SemiBoldItalic_ttf_xml;
  extern TestCMap kTestCabin_BoldItalic_ttf_xml;
  extern TestCMap kTestCabin_Medium_ttf_xml;
  extern TestCMap kTestCabin_Italic_ttf_xml;
  extern TestCMap kTestCabin_Bold_ttf_xml;
  extern TestCMap kTestCabin_Regular_ttf_xml;
  extern TestCMap kTestDawningofaNewDay_ttf_xml;
  extern TestCMap kTestDangrek_ttf_xml;
  extern TestCMap kTestBlackOpsOne_ttf_xml;
  extern TestCMap kTestFrancoisOne_ttf_xml;
  extern TestCMap kTestBowlbyOne_ttf_xml;
  extern TestCMap kTestBowlbyOneSC_ttf_xml;
  extern TestCMap kTestCalligraffiti_ttf_xml;
  extern TestCMap kTestBangers_ttf_xml;
  extern TestCMap kTestAstloch_Regular_ttf_xml;
  extern TestCMap kTestAstloch_Bold_ttf_xml;
  extern TestCMap kTestAngkor_ttf_xml;
  extern TestCMap kTestAbrilFatface_Regular_ttf_xml;
  extern TestCMap kTestCantarell_BoldOblique_ttf_xml;
  extern TestCMap kTestCantarell_Oblique_ttf_xml;
  extern TestCMap kTestCantarell_Bold_ttf_xml;
  extern TestCMap kTestCantarell_Regular_ttf_xml;
  extern TestCMap kTestArvo_Bold_ttf_xml;
  extern TestCMap kTestArvo_Italic_ttf_xml;
  extern TestCMap kTestArvo_BoldItalic_ttf_xml;
  extern TestCMap kTestArvo_Regular_ttf_xml;
  extern TestCMap kTestChewy_ttf_xml;
  extern TestCMap kTestBigshotOne_ttf_xml;
  extern TestCMap kTestChenla_ttf_xml;
  extern TestCMap kTestBayon_ttf_xml;
  extern TestCMap kTestCoustard_Black_ttf_xml;
  extern TestCMap kTestCoustard_Regular_ttf_xml;
  extern TestCMap kTestAmaticSC_Bold_ttf_xml;
  extern TestCMap kTestAmaticSC_Regular_ttf_xml;
  extern TestCMap kTestComfortaa_Light_ttf_xml;
  extern TestCMap kTestComfortaa_Bold_ttf_xml;
  extern TestCMap kTestComfortaa_Regular_ttf_xml;
  extern TestCMap kTestExpletusSans_Bold_ttf_xml;
  extern TestCMap kTestExpletusSans_MediumItalic_ttf_xml;
  extern TestCMap kTestExpletusSans_Medium_ttf_xml;
  extern TestCMap kTestExpletusSans_SemiBold_ttf_xml;
  extern TestCMap kTestExpletusSans_Regular_ttf_xml;
  extern TestCMap kTestExpletusSans_Italic_ttf_xml;
  extern TestCMap kTestExpletusSans_SemiBoldItalic_ttf_xml;
  extern TestCMap kTestExpletusSans_BoldItalic_ttf_xml;
  extern TestCMap kTestAubrey_Regular_ttf_xml;
  extern TestCMap kTestAntic_Regular_ttf_xml;
  extern TestCMap kTestCopse_Regular_ttf_xml;
  extern TestCMap kTestDaysOne_Regular_ttf_xml;
  extern TestCMap kTestActor_Regular_ttf_xml;
  extern TestCMap kTestBentham_Regular_ttf_xml;
  extern TestCMap kTestFedero_Regular_ttf_xml;
  extern TestCMap kTestArimo_Italic_ttf_xml;
  extern TestCMap kTestArimo_BoldItalic_ttf_xml;
  extern TestCMap kTestArimo_Bold_ttf_xml;
  extern TestCMap kTestArimo_Regular_ttf_xml;
  extern TestCMap kTestIMFeDPsc28P_ttf_xml;
  extern TestCMap kTestIMFeGPrm28P_ttf_xml;
  extern TestCMap kTestIMFeENsc28P_ttf_xml;
  extern TestCMap kTestIMFePIit28P_ttf_xml;
  extern TestCMap kTestIMFeDPrm28P_ttf_xml;
  extern TestCMap kTestIMFePIrm28P_ttf_xml;
  extern TestCMap kTestIMFeFCrm28P_ttf_xml;
  extern TestCMap kTestIMFeGPit28P_ttf_xml;
  extern TestCMap kTestIMFeENit28P_ttf_xml;
  extern TestCMap kTestIMFeDPit28P_ttf_xml;
  extern TestCMap kTestIMFeENrm28P_ttf_xml;
  extern TestCMap kTestIMFeGPsc28P_ttf_xml;
  extern TestCMap kTestIMFePIsc28P_ttf_xml;
  extern TestCMap kTestIMFeFCsc28P_ttf_xml;
  extern TestCMap kTestIMFeFCit28P_ttf_xml;
  extern TestCMap kTestBokor_ttf_xml;
  extern TestCMap kTestDidactGothic_ttf_xml;
  extern TestCMap kTestAllerta_Medium_ttf_xml;
  extern TestCMap kTestAllerta_Stencil_ttf_xml;
  extern TestCMap kTestBuda_Light_ttf_xml;
  extern TestCMap kTestBrawler_Regular_ttf_xml;
  extern TestCMap kTestCarterOne_ttf_xml;
  extern TestCMap kTestCandal_ttf_xml;
  extern TestCMap kTestDorsa_Regular_ttf_xml;
  extern TestCMap kTestCrimsonText_BoldItalic_ttf_xml;
  extern TestCMap kTestCrimsonText_Bold_ttf_xml;
  extern TestCMap kTestCrimsonText_Italic_ttf_xml;
  extern TestCMap kTestCrimsonText_Roman_ttf_xml;
  extern TestCMap kTestCrimsonText_Semibold_ttf_xml;
  extern TestCMap kTestCrimsonText_SemiboldItalic_ttf_xml;
  extern TestCMap kTestAmaranth_Italic_ttf_xml;
  extern TestCMap kTestAmaranth_Bold_ttf_xml;
  extern TestCMap kTestAmaranth_Regular_ttf_xml;
  extern TestCMap kTestAmaranth_BoldItalic_ttf_xml;
  extern TestCMap kTestCrushed_ttf_xml;
  extern TestCMap kTestAdamina_Regular_ttf_xml;
  extern TestCMap kTestAldrich_Regular_ttf_xml;
  extern TestCMap kTestFanwoodText_Italic_ttf_xml;
  extern TestCMap kTestFanwoodText_Regular_ttf_xml;
  extern TestCMap kTestAnonymousPro_Regular_ttf_xml;
  extern TestCMap kTestAnonymousPro_Bold_ttf_xml;
  extern TestCMap kTestAnonymousPro_Italic_ttf_xml;
  extern TestCMap kTestAnonymousPro_BoldItalic_ttf_xml;
  extern TestCMap kTestBevan_ttf_xml;
  extern TestCMap kTestArtifika_Regular_ttf_xml;
  extern TestCMap kTestAnton_ttf_xml;
  extern TestCMap kTestBattambang_Regular_ttf_xml;
  extern TestCMap kTestBattambang_Bold_ttf_xml;
  extern TestCMap kTestCarme_Regular_ttf_xml;
  extern TestCMap kTestCherryCreamSoda_ttf_xml;
  extern TestCMap kTestDeliusUnicase_Regular_ttf_xml;
  extern TestCMap kTestComingSoon_ttf_xml;
  extern TestCMap kTestFreehand_ttf_xml;
  extern TestCMap kTestAlice_Regular_ttf_xml;
  extern TestCMap kTestContrail_Regular_ttf_xml;
  extern TestCMap kTestCardo_Bold_ttf_xml;
  extern TestCMap kTestCardo_Italic_ttf_xml;
  extern TestCMap kTestCardo_Regular_ttf_xml;
  extern TestCMap kTestAsset_ttf_xml;
  extern TestCMap kTestChangaOne_Regular_ttf_xml;
  extern TestCMap kTestAclonica_ttf_xml;
  extern TestCMap kTestCraftyGirls_ttf_xml;
  extern TestCMap kTestArchitectsDaughter_ttf_xml;
  extern TestCMap kTestContent_Bold_ttf_xml;
  extern TestCMap kTestContent_Regular_ttf_xml;
  extern TestCMap kTestAbel_Regular_ttf_xml;
  extern TestCMap kTestCuprum_ttf_xml;
  extern TestCMap kTestAndika_R_ttf_xml;

  const TestCMap kAllTestCMaps[] = {
    kTestCousine_BoldItalic_ttf_xml,
    kTestCousine_Bold_ttf_xml,
    kTestCousine_Regular_ttf_xml,
    kTestCousine_Italic_ttf_xml,
    kTestCedarville_Cursive_ttf_xml,
    kTestDancingScript_Bold_ttf_xml,
    kTestDancingScript_Regular_ttf_xml,
    kTestDamion_Regular_ttf_xml,
    kTestAnnieUseYourTelescope_ttf_xml,
    kTestDeliusSwashCaps_Regular_ttf_xml,
    kTestDelius_Regular_ttf_xml,
    kTestCoveredByYourGrace_ttf_xml,
    kTestEBGaramond_Regular_ttf_xml,
    kTestCabinSketch_Bold_ttf_xml,
    kTestAllan_Bold_ttf_xml,
    kTestCoda_Caption_Heavy_ttf_xml,
    kTestCoda_Heavy_ttf_xml,
    kTestForum_Regular_ttf_xml,
    kTestAlike_Regular_ttf_xml,
    kTestCorben_Bold_ttf_xml,
    kTestCaudex_Regular_ttf_xml,
    kTestCaudex_BoldItalic_ttf_xml,
    kTestCaudex_Italic_ttf_xml,
    kTestCaudex_Bold_ttf_xml,
    kTestCabin_MediumItalic_ttf_xml,
    kTestCabin_SemiBold_ttf_xml,
    kTestCabin_SemiBoldItalic_ttf_xml,
    kTestCabin_BoldItalic_ttf_xml,
    kTestCabin_Medium_ttf_xml,
    kTestCabin_Italic_ttf_xml,
    kTestCabin_Bold_ttf_xml,
    kTestCabin_Regular_ttf_xml,
    kTestDawningofaNewDay_ttf_xml,
    kTestDangrek_ttf_xml,
    kTestBlackOpsOne_ttf_xml,
    kTestFrancoisOne_ttf_xml,
    kTestBowlbyOne_ttf_xml,
    kTestBowlbyOneSC_ttf_xml,
    kTestCalligraffiti_ttf_xml,
    kTestBangers_ttf_xml,
    kTestAstloch_Regular_ttf_xml,
    kTestAstloch_Bold_ttf_xml,
    kTestAngkor_ttf_xml,
    kTestAbrilFatface_Regular_ttf_xml,
    kTestCantarell_BoldOblique_ttf_xml,
    kTestCantarell_Oblique_ttf_xml,
    kTestCantarell_Bold_ttf_xml,
    kTestCantarell_Regular_ttf_xml,
    kTestArvo_Bold_ttf_xml,
    kTestArvo_Italic_ttf_xml,
    kTestArvo_BoldItalic_ttf_xml,
    kTestArvo_Regular_ttf_xml,
    kTestChewy_ttf_xml,
    kTestBigshotOne_ttf_xml,
    kTestChenla_ttf_xml,
    kTestBayon_ttf_xml,
    kTestCoustard_Black_ttf_xml,
    kTestCoustard_Regular_ttf_xml,
    kTestAmaticSC_Bold_ttf_xml,
    kTestAmaticSC_Regular_ttf_xml,
    kTestComfortaa_Light_ttf_xml,
    kTestComfortaa_Bold_ttf_xml,
    kTestComfortaa_Regular_ttf_xml,
    kTestExpletusSans_Bold_ttf_xml,
    kTestExpletusSans_MediumItalic_ttf_xml,
    kTestExpletusSans_Medium_ttf_xml,
    kTestExpletusSans_SemiBold_ttf_xml,
    kTestExpletusSans_Regular_ttf_xml,
    kTestExpletusSans_Italic_ttf_xml,
    kTestExpletusSans_SemiBoldItalic_ttf_xml,
    kTestExpletusSans_BoldItalic_ttf_xml,
    kTestAubrey_Regular_ttf_xml,
    kTestAntic_Regular_ttf_xml,
    kTestCopse_Regular_ttf_xml,
    kTestDaysOne_Regular_ttf_xml,
    kTestActor_Regular_ttf_xml,
    kTestBentham_Regular_ttf_xml,
    kTestFedero_Regular_ttf_xml,
    kTestArimo_Italic_ttf_xml,
    kTestArimo_BoldItalic_ttf_xml,
    kTestArimo_Bold_ttf_xml,
    kTestArimo_Regular_ttf_xml,
    kTestIMFeDPsc28P_ttf_xml,
    kTestIMFeGPrm28P_ttf_xml,
    kTestIMFeENsc28P_ttf_xml,
    kTestIMFePIit28P_ttf_xml,
    kTestIMFeDPrm28P_ttf_xml,
    kTestIMFePIrm28P_ttf_xml,
    kTestIMFeFCrm28P_ttf_xml,
    kTestIMFeGPit28P_ttf_xml,
    kTestIMFeENit28P_ttf_xml,
    kTestIMFeDPit28P_ttf_xml,
    kTestIMFeENrm28P_ttf_xml,
    kTestIMFeGPsc28P_ttf_xml,
    kTestIMFePIsc28P_ttf_xml,
    kTestIMFeFCsc28P_ttf_xml,
    kTestIMFeFCit28P_ttf_xml,
    kTestBokor_ttf_xml,
    kTestDidactGothic_ttf_xml,
    kTestAllerta_Medium_ttf_xml,
    kTestAllerta_Stencil_ttf_xml,
    kTestBuda_Light_ttf_xml,
    kTestBrawler_Regular_ttf_xml,
    kTestCarterOne_ttf_xml,
    kTestCandal_ttf_xml,
    kTestDorsa_Regular_ttf_xml,
    kTestCrimsonText_BoldItalic_ttf_xml,
    kTestCrimsonText_Bold_ttf_xml,
    kTestCrimsonText_Italic_ttf_xml,
    kTestCrimsonText_Roman_ttf_xml,
    kTestCrimsonText_Semibold_ttf_xml,
    kTestCrimsonText_SemiboldItalic_ttf_xml,
    kTestAmaranth_Italic_ttf_xml,
    kTestAmaranth_Bold_ttf_xml,
    kTestAmaranth_Regular_ttf_xml,
    kTestAmaranth_BoldItalic_ttf_xml,
    kTestCrushed_ttf_xml,
    kTestAdamina_Regular_ttf_xml,
    kTestAldrich_Regular_ttf_xml,
    kTestFanwoodText_Italic_ttf_xml,
    kTestFanwoodText_Regular_ttf_xml,
    kTestAnonymousPro_Regular_ttf_xml,
    kTestAnonymousPro_Bold_ttf_xml,
    kTestAnonymousPro_Italic_ttf_xml,
    kTestAnonymousPro_BoldItalic_ttf_xml,
    kTestBevan_ttf_xml,
    kTestArtifika_Regular_ttf_xml,
    kTestAnton_ttf_xml,
    kTestBattambang_Regular_ttf_xml,
    kTestBattambang_Bold_ttf_xml,
    kTestCarme_Regular_ttf_xml,
    kTestCherryCreamSoda_ttf_xml,
    kTestDeliusUnicase_Regular_ttf_xml,
    kTestComingSoon_ttf_xml,
    kTestFreehand_ttf_xml,
    kTestAlice_Regular_ttf_xml,
    kTestContrail_Regular_ttf_xml,
    kTestCardo_Bold_ttf_xml,
    kTestCardo_Italic_ttf_xml,
    kTestCardo_Regular_ttf_xml,
    kTestAsset_ttf_xml,
    kTestChangaOne_Regular_ttf_xml,
    kTestAclonica_ttf_xml,
    kTestCraftyGirls_ttf_xml,
    kTestArchitectsDaughter_ttf_xml,
    kTestContent_Bold_ttf_xml,
    kTestContent_Regular_ttf_xml,
    kTestAbel_Regular_ttf_xml,
    kTestCuprum_ttf_xml,
    kTestAndika_R_ttf_xml
  };
}				// namespace sfntly

#endif //SFNTLY_CPP_SRC_TEST_CMAP_TEST_DATA_H_
